rolling_average_labels = [
    'FG3_PCT', 'REB', 'PTS', 'FGA', 'FT_PCT', 'OREB', 'AST', 'WL', 'MIN',
    'FG_PCT', 'FG3M', 'FTA', 'FG3A', 'TOV', 'FTM', 'FGM', 'PLUS_MINUS', 'STL',
    'PTS_ROLL_AVG',
    'MIN_ROLL_AVG',
    'FG_PCT_ROLL_AVG',
    'FGM_ROLL_AVG',
    'FGA_ROLL_AVG',
    'FG3M_ROLL_AVG',
    'FG3A_ROLL_AVG',
    'FG3_PCT_ROLL_AVG',
    'FT_PCT_ROLL_AVG',
    'REB_ROLL_AVG',
    'AST_ROLL_AVG',
    'FGM_FGA_RATIO',
    '3PM_3PA_RATIO',
    'REST_IMPACT',
    'DAYS_SINCE_LAST_GAME',
    'TRUE_SHOOTING_PCT',
    'BACK_TO_BACK',
    'OPP_W_PCT_RANK',
    'OPP_STL_RANK', 'OPP_PF_RANK',
    'OPP_PTS',
    'OPP_REB',
    'OPP_AST',
    'OPP_STL',
    'OPP_BLK',
    'TOTAL_POINTS',
    'HOME',
    'PTS_LAG_1',
    'PTS_LAG_2',
    'PTS_LAG_3',
    'PTS_LAG_4',
    'PTS_LAG_5',
    'OPP_STRENGTH',
    'OPP_PERFORMANCE_IMPACT',
    'OPP_OFFENSIVE_STRENGTH',
    'OPP_DEFENSIVE_STRENGTH'
]
