rolling_average_labels = [
    'FG3_PCT', 'REB', 'PTS', 'FGA', 'FT_PCT', 'OREB', 'AST', 'WL', 'MIN',
    'FG_PCT', 'FG3M', 'FTA', 'FG3A', 'TOV', 'FTM', 'FGM', 'PLUS_MINUS', 'STL',
    'PTS_ROLL_AVG',
    'PTS_STD_AVG',
    'MIN_ROLL_AVG',
    'FG_PCT_ROLL_AVG',
    'FGM_ROLL_AVG',
    'FGA_ROLL_AVG',
    'FG3M_ROLL_AVG',
    'FG3GA_ROLL_AVG',
    'FG3_PCT_ROLL_AVG',
    'FTM_PCT_ROLL_AVG',
    'FTA_PCT_ROLL_AVG',
    'FT_PCT_ROLL_AVG',
    'REB_ROLL_AVG',
    'AST_ROLL_AVG',
    'PTS_LAG_1',
    'PTS_LAG_2',
    'PTS_LAG_3',
    'PTS_LAG_4',
    'PTS_LAG_5',
    'PER',
    'PTS_X_MIN',
    'FGM_FGA_RATIO',
    '3PM_3PA_RATIO',
    'REST_IMPACT',
    'DAYS_SINCE_LAST_GAME',
    'TRUE_SHOOTING_PCT',
    'BACK_TO_BACK',
    'ROLLING_PER'
]
