rolling_average_labels = [
    'FG3_PCT', 'REB', 'PTS', 'FGA', 'FT_PCT', 'OREB', 'AST', 'WL', 'MIN',
    'FG_PCT', 'FG3M', 'FTA', 'FG3A', 'TOV', 'FTM', 'FGM', 'PLUS_MINUS', 'STL',
    'points_rolling_avg',
    'minutes_rolling_avg',
    'fg_pct_rolling_avg',
    'reb_rolling_avg',
    'ast_rolling_avg',
    'fgm_rolling_avg',
    'fga_rolling_avg',
    'fg3m_rolling_avg',
    'fg3a_rolling_avg',
    'fg3_pct_rolling_avg',
    'ftm_pct_rolling_avg',
    'fta_pct_rolling_avg',
    'ft_pct_rolling_avg',
    'days_since_last_game',
    'points_std_rolling',
    "pts_lag_1",
    "pts_lag_2"
]
